version: 2
updates:
- package-ecosystem: npm
  directory: "/phaser-isometric"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: webpack
    versions:
    - 5.23.0
    - 5.24.1
    - 5.26.0
    - 5.26.3
    - 5.34.0
    - 5.35.1
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: webpack-cli
    versions:
    - 4.4.0
